[[build.env]] 
    name = "GOOGLE_RUNTIME_VERSION" 
    value = "3.10.x"

[[build.env]]
    name = "GOOGLE_ENTRYPOINT"
    value = "python3 main.py"

[[build.env]]
    name = "PORT"
    value = "8080"